---
title: "Mini-Project 2"
author: "Your Name Here"
date: "October 31, 2017"
output: html_document
---
=======
>>>>>>> 4759b1f54f9b57a815caa8140d7cdf1da8ce1033
## Loading the data

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
library(tidyverse)
library(gridExtra)
library(cowplot)
library(grid)
```
pull down, make changes, save file, git, stage file (click the check), commit, pull, push 

```{r}
test2<-contributions%>%
  inner_join(house_elections, by=c("cand_id"="fec_id"))

test3<-test2%>%
  inner_join(candidates, by="cand_id")
```

```{r}
total<-test3%>%
  group_by(cand_id, cand_name, cand_party_affiliation)%>%
  mutate(posneg=ifelse(transaction_amt>0, "positive","negative"))
```

```{r}
totalcont<-total%>%
  group_by(cand_id, cand_name)%>%
  summarise(against=sum(ifelse(posneg=="negative", transaction_amt, 0)),
            support=sum(ifelse(posneg=="positive", transaction_amt, 0)))
```

```{r}
outcome<-totalcont%>%
  left_join(house_elections, by=c("cand_id"="fec_id"))

top50<-outcome%>%
  arrange(desc(support))%>%
  head(50)

mostagainst<-outcome%>%
  arrange(desc(against))%>%
  head(50)
```

```{r}
final <- outcome %>%
  filter(party=="D" | party=="R")%>%
  arrange(desc(general_votes)) %>%
  head(50)
final$cand_name <- factor(final$cand_name, levels = final$cand_name[order(final$support)])
```

```{r, message=FALSE}
testplot <- ggplot(final, aes(x = cand_name, y = support, fill=party)) +
  geom_bar(stat="identity") +
  theme(axis.title.x = element_text(), 
        axis.text.x = element_text(size = 9),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 5.5, hjust=.5), 
        axis.ticks.y = element_blank(), 
        plot.margin = unit(c(2,0,3,3), "mm"),
        legend.position = c(.2,.3)) +
  scale_y_reverse() +
  coord_flip()+
  scale_y_continuous(breaks=c(0, 1000000,2000000,3000000), labels=c("0", "1M", "2M", "3M"))+
  scale_fill_discrete(name="Party", breaks = c("D", "N", "R"), labels=c("Democrat", "New Progressive", "Republican"))+
  ylab("Support")

testplot2 <- ggplot(final, aes(x = cand_name, y = against, fill=party)) +
  geom_bar(stat="identity") +
  theme(axis.title.x = element_text(),
        axis.text.x = element_text(size = 9),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        plot.margin = unit(c(2,-4,3,0), "mm")) +
  scale_fill_discrete(guide=FALSE)+
  coord_flip() +
  scale_y_continuous(breaks=c(0, -100000, -200000), limits=c(-1000000,0), labels=c("0", "-100K", "-200K" ))+
   theme(axis.line.y=element_line(color="white"))+
  annotate("segment", x = 0, xend = 51, y = -1, yend =-1,
  colour = "black")+
  ylab("Against")

plot_grid(testplot2, testplot, ncol = 2)

final$cand_name <- factor(final$cand_name, levels = final$cand_name[order(desc(final$general_votes))])
ggplot(final, aes(x=cand_name, y=general_votes, color=party))+
            geom_point()+
  theme(axis.text.x = element_text(angle=45, size=7, hjust=1))
```



```{r}

final <- outcome %>%
  filter(party=="D" | party=="R")%>%
  arrange(desc(general_votes)) %>%
  head(50)
final$cand_name <- factor(final$cand_name, levels = final$cand_name[order(final$support)])

testplot <- ggplot(final, aes(x = cand_name, y = support, fill=party)) +
  geom_bar(stat="identity") +
  theme(axis.title.x = element_text(), 
        axis.text.x = element_text(size = 9),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 5.5, hjust=.5), 
        axis.ticks.y = element_blank(), 
        plot.margin = unit(c(2,0,3,3), "mm"),
        legend.position = c(.2,.3)) +
  scale_y_reverse() +
  coord_flip()+
  scale_y_continuous(breaks=c(0, 1000000,2000000,3000000), labels=c("0", "1M", "2M", "3M"))+
  scale_fill_discrete(name="Party", breaks = c("D", "N", "R"), labels=c("Democrat", "New Progressive", "Republican"))+
  ylab("Support")

testplot2 <- ggplot(final, aes(x = cand_name, y = general_votes, fill=party)) +
  geom_bar(stat="identity") +
  theme(axis.title.x = element_text(),
        axis.text.x = element_text(size = 9),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        plot.margin = unit(c(2,-4,3,0), "mm")) +
  scale_fill_discrete(guide=FALSE)+
  coord_flip() +
  scale_y_continuous(breaks=c(1000000, 750000,500000,250000, 0 ), labels=c("1M", ".75M", ".5M", ".25M", "0"))+
  ylim(1000000,0)+
  ylab("General Election Votes")

plot_grid(testplot2, testplot, ncol = 2)
```